# Contains some edge case handing required for getting Python
# development tools to build and run on OS X. Note that this will
# unlink and install a specific version of swig (2.0.12).

# Homebrew's default swig 3.x plays poorly with some of our python
# depenencies, so install brew 2.x if needed.
- name: HACK - install old version of swig
  shell: brew install homebrew/versions/swig2

# http://stackoverflow.com/questions/20325473/error-installing-python-image-library-using-pip-on-mac-os-x-10-9
- name: HACK - Checking for freetype
  stat: path=/usr/local/include/freetype
  register: freetype_stat

- name: HACK - Linking freetype
  command: ln -s /usr/local/include/freetype2 /usr/local/include/freetype
  when: not freetype_stat.stat.exists

# Build of enthought enable fails for some kind of legacy OS X
# library dependency. If using a recent version of OS X, move the
# offending to properly resolve build.
# https://trac.macports.org/ticket/35735?cversion=0&cnum_hist=11
- name: HACK - Checking to for legacy uuid.h
  stat: path=/usr/local/include/uuid/uuid.h
  register: uuid_stat

- name: HACK - Move /usr/local/include/uuid/uuid.h
  command: >
             mv -fv /usr/local/include/uuid/uuid.h
                    /usr/local/include/uuid/uuid.h.bak
  when: uuid_stat.stat.exists
